#!/bin/sh

# Build main code
ghc -optl"-Wl,-read_only_relocs,suppress" -tmpdir tmp -hidir hi -odir obj -fext-core -fexcess-precision -funbox-strict-fields -threaded -rtsopts -fwarn-missing-signatures -Wall -O2 -fspec-constr -fliberate-case -fstatic-argument-transformation -fspec-constr-count=10 Main.hs -o ../crocodile $1 $2 $3 $4 $5 $6 $7 $8 $9

# Tidy up
mv *.hcr core/

# Unit test
scripts/unit_test

rm obj/Main.o

# Build test suite
ghc -optl"-Wl,-read_only_relocs,suppress" -tmpdir tmp -hidir hi -odir obj -fext-core -fexcess-precision -funbox-strict-fields -threaded -rtsopts -fwarn-missing-signatures -Wall -O2 -fspec-constr -fliberate-case -fstatic-argument-transformation Tests/HemisphereTest/HemisphereTest.hs -o Tests/HemisphereTest/HemisphereTest $1 $2 $3 $4 $5 $6 $7 $8 $9

rm obj/Main.o

ghc -optl"-Wl,-read_only_relocs,suppress" -tmpdir tmp -hidir hi -odir obj -fext-core -fexcess-precision -funbox-strict-fields -threaded -rtsopts -fwarn-missing-signatures -Wall -O2 -fspec-constr -fliberate-case -fstatic-argument-transformation Tests/RandomUVTest/RandomUVTest.hs -o Tests/RandomUVTest/RandomUVTest $1 $2 $3 $4 $5 $6 $7 $8 $9

