#!/bin/sh
ghc -tmpdir tmp -hidir hi -odir obj --make -O2 -fext-core -fexcess-precision -funbox-strict-fields Main.hs -o ../haskell-render -threaded -rtsopts -fwarn-missing-signatures -Wall $1 $2 $3 $4 $5 $6 $7 $8 $9
mv *.hcr core/
