#!/bin/sh
ghc -tmpdir tmp -hidir hi -odir obj -fext-core -fexcess-precision -funbox-strict-fields -threaded -rtsopts -fwarn-missing-signatures -Wall -O2 Main.hs -o ../crocodile $1 $2 $3 $4 $5 $6 $7 $8 $9
mv *.hcr core/
