#!/bin/sh
ghc -tmpdir tmp -hidir hi -odir obj --make -O2 -fexcess-precision -funfolding-use-threshold=16 -funbox-strict-fields Main.hs -o ../haskell-render -funfolding-keeness-factor=10 -fwarn-missing-signatures -Wall -feager-blackholing -prof -auto-all -caf-all -rtsopts

